title: Alberto Pontini
description: Web Developer
url: apontini.me
author: apontini
lang: en_GB
social:
  name: Alberto Pontini
  links:
    - https://twitter.com/AlbertoPontini
    - https://www.linkedin.com/in/alberto-pontini/
    - https://github.com/apontini
plugins:
  - jekyll-seo-tag